version: "3"

services:
  plex:
    container_name: plex
    environment:
      - TZ=${TZ}
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP=${ADVERTISE_IP}
    image: plexinc/pms-docker:1.18.7.2457-77cb9455c
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.custom.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.custom.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.custom.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.custom.headers.frameDeny=true"
      - "traefik.http.middlewares.custom.headers.sslredirect=true"
      - "traefik.http.middlewares.custom.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.custom.headers.stsPreload=true"
      - "traefik.http.middlewares.custom.headers.stsSeconds=315360000"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN_NAME}`)"
      - "traefik.http.routers.plex.tls.certresolver=letsencrypt"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
    networks:
      - traefik_proxy
    restart: always
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/plex_config:/config
      - ${USER_DIR}/tmp/plex_tmp:/transcode
      - /media/nas:/media

  tautulli:
    container_name: tautulli
    environment:
      - TZ=${TZ}
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
    image: tautulli/tautulli:v2.2.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.custom.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.custom.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.custom.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.custom.headers.frameDeny=true"
      - "traefik.http.middlewares.custom.headers.sslredirect=true"
      - "traefik.http.middlewares.custom.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.custom.headers.stsPreload=true"
      - "traefik.http.middlewares.custom.headers.stsSeconds=315360000"
      - "traefik.http.routers.tautulli.entrypoints=websecure"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.${DOMAIN_NAME}`)"
      - "traefik.http.routers.tautulli.tls.certresolver=letsencrypt"
    networks:
      - traefik_proxy
    restart: always
    ports:
      - "8181:8181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/plex_config/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro
      - ./app/tautulli_config:/config

networks:
  traefik_proxy:
    external: true
